website/models.py
from flask_login import UserMixin
from . import db


class User(UserMixin, db.Model):
    # primary keys are required by SQLAlchemy
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
import os
import numpy as np
from os import path
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model
from keras_preprocessing.image import load_img

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = '9OLWxND4o83j4K4iuopO'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'

    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from .models import User

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    from .views import view as view_blueprint
    app.register_blueprint(view_blueprint)

    from .predict import predict as predict_blueprint
    app.register_blueprint(predict_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app


def create_database(app):
    if not path.exists("website/instance/db.sqlite"):
        db.create_all(app=app)
        print("Created database!")

website/auth.py
from flask import Flask, render_template, request, Blueprint
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required
from .models import User
from . import db

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET'])
def login():
    return render_template('login.html')


@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))

    #work here
    login_user(user, remember=remember)
    return redirect(url_for('view.hello'))


@auth.route('/signup', methods=['GET'])
def signup():
    return render_template('signup.html')


@auth.route('/signup', methods=['POST'])
def signup_post():

    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first()

    if user:
        flash('Email address already exists')
        return redirect(url_for('auth.login'))

    new_user = User(email=email, name=name,
                    password=generate_password_hash(password, method='sha256'))

    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    #work here
    return redirect(url_for('view.hello'))

website/views.py
from flask import Flask, render_template, request, Blueprint
from flask_login import login_required, current_user

view = Blueprint('view', __name__)


@view.route('/', methods=['GET'])
def hello():
    return render_template('index.html')

@view.route('/contact-us', methods=['GET'])
def contact():
    return render_template('contact.html', name=current_user.name)

@view.route('/thank-you', methods=['GET'])
def thank():
    return render_template('thankU.html', name=current_user.name)

@view.route('/404', methods=['GET'])
def error():
    return render_template('404.html', name=current_user.name)

@view.route('/team', methods=['GET'])
def team():
    return render_template('team.html', name=current_user.name)

@view.route('/profile')
@login_required
def profile():
    return "Kaam Chal Raha hai bhai thoda ruko"


@view.route('/blog', methods=['GET'])
def blog():
    return render_template('blog.html', name=current_user.name)


@view.route('/blog/Melanoma', methods=['GET'])
def blog_melanoma():
    return render_template('Melanoma.html', name=current_user.name)


@view.route('/blog/Dermatitis', methods=['GET'])
def blog_dermatitis():
    return render_template('Dermatitis.html', name=current_user.name)


@view.route('/blog/Eczema', methods=['GET'])
def blog_Eczema():
    return render_template('Eczema.html', name=current_user.name)


@view.route('/blog/Psoriasis', methods=['GET'])
def blog_Psoriasis():
    return render_template('Psoriasis.html', name=current_user.name)

website/templates/Dermatitis.html
{% extends "base.html" %}

{% block content %}
<div>
  <div class="breadcrumbs">
    <div class="page-header d-flex align-items-center" style="background-image: url('');">
      <div class="container position-relative">
        <div class="row d-flex justify-content-center">
          <div class="col-lg-6 text-center">
            <p>The Model predicted the image as </p>
            <h2>Dermatitis.</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
  <section id="blog" class="blog">
    <div class="container" data-aos="fade-up">
  
      <div class="row g-5">
  
        <div class="col-lg-8">
  
          <article class="blog-details">
  
            <div class="post-img">
              <img src="assets/img/blog/blog-1.jpg" alt="IMG Not Available" class="img-fluid">
            </div>
  
            <h2 class="title">Basic information about Dermatitis.</h2>
  
            <div class="content">
              <p>
                Dermatitis is a general term that describes a common skin irritation. It has many causes and forms and
                usually involves itchy, dry skin or a rash. Or it might cause the skin to blister, ooze, crust or
                flake off.
              </p>
  
              <p>
                Three common types of this condition are atopic dermatitis (eczema), seborrheic dermatitis and
                contact dermatitis.
  
                Dermatitis isn't contagious, but it can make you feel uncomfortable and self-conscious. Moisturizing
                regularly helps control the symptoms. Treatment may also include medicated ointments, creams and
                shampoos.
              </p>
  
              <blockquote>
                <div>
                  <h4>Symptoms:</h4>
                  <p> 1. Itchiness (pruritus).</p>
                  <p> 2. Dry skin.</p>
                  <p> 3. Rash on swollen skin that varies in color depending on your skin color.</p>
                  <p> 4. Blisters, perhaps with oozing and crusting.</p>
                  <p> 5. Flaking skin (dandruff).</p>
                  <p> 6. Thickened skin.</p>
                  <p> 7. Bumps in hair follicles</p>
                </div>
              </blockquote>
  
  
              <h3>When to see a doctor ?</h3>
  
              <p>
                1. You're so uncomfortable that you're losing sleep or are distracted from your daily routines. <br>
                2. Your skin becomes painful. <br>
                3. You suspect that your skin is infected. <br>
                4. You've tried self-care steps but your signs and symptoms persist.
              </p>
  
  
  
            </div><!-- End post content -->
  
  
          </article><!-- End blog post -->
  
          <div class="post-author d-flex align-items-center">
            <img src="assets/img/blog/blog-author.jpg" class="rounded-circle flex-shrink-0" alt="Auhtor Img">
            <div>
              <h4>Jane Smith</h4>
              <div class="social-links">
                <a href="https://twitter.com/#"><i class="bi bi-twitter"></i></a>
                <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
              </div>
              <p>
                Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas repellat
                voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
              </p>
            </div>
          </div><!-- End post author -->
  
  
  
        </div><!-- End blog comments -->
  
      </div>
  
  </section>
</div><!-- End Blog Details Section -->

{% endblock %}

website/templates/Eczema.html
{% extends "base.html" %}

{% block content %}
<div class="breadcrumbs">
  <div class="page-header d-flex align-items-center" style="background-image: url('');">
    <div class="container position-relative">
      <div class="row d-flex justify-content-center">
        <div class="col-lg-6 text-center">
          <p>The Model predicted the image as </p>
          <h2>Eczema.</h2>
        </div>
      </div>
    </div>
  </div>
</div>
<section id="blog" class="blog">
  <div class="container" data-aos="fade-up">

    <div class="row g-5">

      <div class="col-lg-8">

        <article class="blog-details">

          <div class="post-img">
            <img src="assets/img/blog/blog-1.jpg" alt="IMG Not Available" class="img-fluid">
          </div>

          <h2 class="title">Basic information about Eczema.</h2>

          <div class="content">
            <p>Eczema is a condition in which patches of skin become inflamed, itchy, cracked, and rough.
              Some types can also cause blisters.</p>
            <p>
              Different types and stages of eczema affect 31.6 million people in the United States, which
              equals more
              than 10% of the population.Many people use the word eczema when referring to atopic
              dermatitis, which is
              the most common type. The term atopic refers to a collection of conditions that involve the
              immune
              system, including atopic dermatitis, asthma, and hay fever. The word dermatitis refers to
              inflammation
              of the skin. Certain foods, such as nuts and dairy, can trigger symptoms of eczema.
              Environmental
              triggers can include smoke, pollen, soaps, and fragrances. Eczema is not contagious.
            </p>

            <p>
              About a quarter of children in the U.S. have the condition, as well as 10% of African
              Americans, 13%
              of Asian Americans and Pacific Islanders, 13% of Native Americans, and 11% of people who are
              white.Some people outgrow the condition, while others will continue to have it throughout
              adulthood.
              This article will explain what eczema is and discuss its symptoms, treatments, causes, and
              types.
            </p>

            <blockquote>
              <div>
                <h4>Symptoms:</h4>
                <p>1. Dry, scaly skin</p>
                <br>
                <p> 2. Skin flushing </p>
                <br>
                <p>3. Itching </p>
                <br>
                <p>4. Open, crusted, or weeping sores. </p>
                <br>
              </div>
            </blockquote>


            <h3>People with severe eczema may need more intensive treatment to relieve their symptoms.
              Continuous
              rubbing and scratching can also lead to skin infections.</h3>

            <p>
              1. Rashes that appear behind the creases of elbows or knees. <br>
              2. Rashes that appear on the neck, wrists, ankles, and the crease between the buttocks and
              legs
              bumpy rashes. <br>
              3. Rashes that can become lighter or darker. <br>
              4. Skin thickening, also known as lichenification, which can then develop into a permanent
              itch. <br>
            </p>



          </div><!-- End post content -->


        </article><!-- End blog post -->

        <div class="post-author d-flex align-items-center">
          <img src="assets/img/blog/blog-author.jpg" class="rounded-circle flex-shrink-0" alt="Auhtor Img">
          <div>
            <h4>Jane Smith</h4>
            <div class="social-links">
              <a href="https://twitter.com/#"><i class="bi bi-twitter"></i></a>
              <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
              <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
            </div>
            <p>
              Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas
              repellat
              voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
            </p>
          </div>
        </div><!-- End post author -->



      </div><!-- End blog comments -->

    </div>

</section><!-- End Blog Details Section -->

{% endblock %}

website/templates/Melanoma.html
{% extends "base.html" %}

{% block content %}
<div class="breadcrumbs">
    <div class="page-header d-flex align-items-center" style="background-image: url('');">
        <div class="container position-relative">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-6 text-center">
                    <p>The Model predicted the image as </p>
                    <h2>Melanoma.</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<section id="blog" class="blog">
    <div class="container" data-aos="fade-up">

        <div class="row g-5">

            <div class="col-lg-8">

                <article class="blog-details">

                    <div class="post-img">
                        <img src="assets/img/blog/blog-1.jpg" alt="IMG Not Available" class="img-fluid">
                    </div>

                    <h2 class="title">Basic information about Melanoma.</h2>

                    <div class="content">
                        <p> Melanoma, the most serious type of skin cancer, develops in the cells (melanocytes) that
                            produce
                            melanin the pigment that gives your skin its color. Melanoma can also form in your eyes and,
                            rarely,
                            inside your body, such as in your nose or throat.</p>
                        <p>
                            The exact cause of all melanomas isn't clear, but exposure to ultraviolet (UV) radiation
                            from sunlight
                            or tanning lamps and beds increases your risk of developing melanoma. Limiting your exposure
                            to UV
                            radiation can help reduce your risk of melanoma.
                        </p>

                        <blockquote>
                            <div>
                                <h3>Signs Of Melanoma: </h3>
                                <p>1. Asymmetry.</p> <br>
                                <p>2. Border.</p> <br>
                                <p>3. Diameter.</p> <br>
                                <p>4. Evolvings.</p> <br>

                            </div>
                        </blockquote>

                        <p>
                            The risk of melanoma seems to be increasing in people under 40, especially women. Knowing
                            the warning
                            signs of skin cancer can help ensure that cancerous changes are detected and treated before
                            the cancer
                            has spread. Melanoma can be treated successfully if it is detected early.
                        </p>

                        <h3>Symptoms. </h3>
                        <p>
                            Melanomas can develop anywhere on your body. They most often develop in areas that have had
                            exposure
                            to the sun, such as your back, legs, arms and face.</p>
                        Melanomas can also occur in areas that don't receive much sun exposure, such as the soles of
                        your feet,
                        palms of your hands and fingernail beds. These hidden melanomas are more common in people with
                        darker
                        skin.
                        </p>



                    </div><!-- End post content -->


                </article><!-- End blog post -->

                <div class="post-author d-flex align-items-center">
                    <img src="assets/img/blog/blog-author.jpg" class="rounded-circle flex-shrink-0" alt="Auhtor Img">
                    <div>
                        <h4>Jane Smith</h4>
                        <div class="social-links">
                            <a href="https://twitter.com/#"><i class="bi bi-twitter"></i></a>
                            <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                            <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
                        </div>
                        <p>
                            Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas
                            repellat
                            voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
                        </p>
                    </div>
                </div><!-- End post author -->



            </div><!-- End blog comments -->

        </div>

</section><!-- End Blog Details Section -->

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Base Plate</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <link rel="shortcut icon" href="../static/img/dermatology.png">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />

  <link
    href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
    rel="stylesheet">


  <link href="../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="../static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="../static/vendor/aos/aos.css" rel="stylesheet">
  <link href="../static/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="../static/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">


  <link href="../static/css/main.css" rel="stylesheet">

</head>

<body>



  <header id="header" class="header d-flex align-items-center">

    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
      <a href="/" class="logo d-flex align-items-center">
        <h1>Dermat<span>.</span></h1>
      </a>
      <nav id="navbar" class="navbar" style="background-color: #00d1b2;">
        <ul>
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('view.blog')}}">Blog</a></li>
          {% endif %}
          {% if not current_user.is_authenticated %}
          <li><a href="{{url_for('auth.login')}}">Login</a></li>
          {% endif %}
          {% if not current_user.is_authenticated %}
          <li><a href="{{url_for('auth.signup')}}">Sign Up</a></li>
          {% endif %}
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('view.error')}}">Consult</a></li>
          {% endif %}
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('view.error')}}">
              {% if current_user.is_authenticated %}
              {{current_user.name}}
              {% else %}
              User
              {% endif %}
            </a></li>
          {% endif %}
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('view.contact')}}">Contact</a></li>
          {% endif %}
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('auth.logout')}}">Log Out</a></li>
          {% endif %}
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('view.team')}}">Team</a></li>
          {% endif %}
        </ul>
      </nav>

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header>


  <main id="main">


    {% block content %}
    {% endblock %}

  </main>
  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>
  <div id="preloader"></div>

  <footer id="footer" class="footer">

    <div class="container mt-4">
      <div class="copyright">
        &copy; Copyright <strong><span>Dermat</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        Project by <a href="#">Group A3</a>
      </div>
    </div>

  </footer>

  <script src="../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="../static/vendor/aos/aos.js"></script>
  <script src="../static/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="../static/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="../static/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="../static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="../static/vendor/php-email-form/validate.js"></script>


  <script src="../static/js/main.js"></script>

</body>

</html>

website/templates/blog.html
{% extends "base.html" %}

{% block content %}

<main id="main">

  <!-- ======= Breadcrumbs ======= -->
  <div class="breadcrumbs">
    <div class="page-header d-flex align-items-center" style="background-image: url('');">
      <div class="container position-relative">
        <div class="row d-flex justify-content-center">
          <div class="col-lg-6 text-center">
            <h2>Blog</h2>
          </div>
        </div>
      </div>
    </div>
    <nav>
      <div class="container">
        <ol>
          <li><a href="index.html">Home</a></li>
          <li>Blog</li>
        </ol>
      </div>
    </nav>
  </div><!-- End Breadcrumbs -->

  <!-- ======= Blog Section ======= -->
  <section id="blog" class="blog">
    <div class="container" data-aos="fade-up">

      <div class="row gy-4 posts-list">

        <div class="col-xl-4 col-md-6">
          <article>

            <div class="post-img">
              <img src="../static/img/blog/blog-1.jpg" alt="" class="img-fluid">
            </div>

            <p class="post-category">Melanoma</p>

            <h2 class="title">
              <a href="{{url_for('view.blog_melanoma')}}">Basic information about Melanoma.</a>
            </h2>

            <div class="d-flex align-items-center">
              <!-- <img src="../static/img/blog/blog-author.jpg" alt="" class="img-fluid post-author-img flex-shrink-0"> -->
              <div class="post-meta">
                <p class="post-author-list">Dr. ABC</p>
                <p class="post-date">
                  <time datetime="2023-01-01">__</time>
                </p>
              </div>
            </div>

          </article>
        </div><!-- End post list item -->

        <div class="col-xl-4 col-md-6">
          <article>

            <div class="post-img">
              <img src="../static/img/blog/blog-2.jpg" alt="" class="img-fluid">
            </div>

            <p class="post-category">Eczema</p>

            <h2 class="title">
              <a href="{{url_for('view.blog_Eczema')}}">Basic information about Eczema</a>
            </h2>

            <div class="d-flex align-items-center">
              <!-- <img src="../static/img/blog/blog-author-2.jpg" alt="" class="img-fluid post-author-img flex-shrink-0"> -->
              <div class="post-meta">
                <p class="post-author-list">Dr. ABC</p>
                <p class="post-date">
                  <time datetime="2023-01-01">__</time>
                </p>
              </div>
            </div>

          </article>
        </div><!-- End post list item -->

        <div class="col-xl-4 col-md-6">
          <article>

            <div class="post-img">
              <img src="../static/img/blog/blog-3.webp" alt="" class="img-fluid">
            </div>

            <p class="post-category">Psoriasis</p>

            <h2 class="title">
              <a href="{{url_for('view.blog_Psoriasis')}}">Basic information about Psoriasis</a>
            </h2>

            <div class="d-flex align-items-center">
              <!-- <img src="../static/img/blog/blog-author-3.jpg" alt="" class="img-fluid post-author-img flex-shrink-0"> -->
              <div class="post-meta">
                <p class="post-author-list">Dr. ABC</p>
                <p class="post-date">
                  <time datetime="2023-01-01">__</time>
                </p>
              </div>
            </div>

          </article>
        </div><!-- End post list item -->

        <div class="col-xl-4 col-md-6">
          <article>

            <div class="post-img">
              <img src="../static/img/blog/blog-4.jpg" alt="" class="img-fluid">
            </div>

            <p class="post-category">Dermatitis</p>

            <h2 class="title">
              <a href="{{url_for('view.blog_dermatitis')}}">Basic information about Dermatitis</a>
            </h2>

            <div class="d-flex align-items-center">
              <!-- <img src="../static/img/blog/blog-author-4.jpg" alt="" class="img-fluid post-author-img flex-shrink-0"> -->
              <div class="post-meta">
                <p class="post-author-list">Dr. ABC</p>
                <p class="post-date">
                  <time datetime="2023-01-01">__</time>
                </p>
              </div>
            </div>

          </article>
        </div><!-- End post list item -->



      </div>
  </section><!-- End Blog Section -->

</main><!-- End #main -->

{% endblock %}

website/templates/contact.html
{% extends "base.html" %}

{% block content %}
<div>
    <div class="breadcrumbs">
        <div class="page-header d-flex align-items-center" style="background-image: url('');">
            <div class="container position-relative">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6 text-center">
                        <h2>Contact.</h2>
                    </div>
                </div>
            </div>
        </div>
        <nav>
            <div class="container">
                <ol>
                    <li><a href="{{url_for('view.hello')}}">Home</a></li>
                    <li>Contact</li>
                </ol>
            </div>
        </nav>
    </div><!-- End Breadcrumbs -->

    <div class="container-xxl py-6">
        <div class="container">
            <div class="mx-auto text-center wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">

                <h2 class="mb-5">If You Have Any Query, Please Feel Free Contact Us</h2>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-7 wow fadeInUp" data-wow-delay="0.3s">
                    <form method="POST" action="https://formsubmit.co/kirakamikirasama@gmail.com">
                        <!-- work Here -->
                        <input type="hidden" name="_next" value="http://localhost:5000/thank-you">
                        <input type="hidden" name="_captcha" value="false">
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" name="name" class="form-control" id="name"
                                        placeholder="Your Name">
                                    <label for="name">Your Name</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="email" name="email" class="form-control" id="email"
                                        placeholder="Your Email" required>
                                    <label for="email">Your Email</label>
                                </div>
                            </div>

                            <input type="hidden" name="_subject" value="Dermat. Query {{name}}">


                            <div class="col-12">
                                <div class="form-floating">
                                    <textarea name="message" class="form-control" placeholder="Leave a message here"
                                        id="message" style="height: 150px"></textarea>
                                    <label for="message">Message</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary w-100 py-3" type="submit">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br><br>
</div>

{% endblock %}

website/templates/thankU.html
{% extends "base.html" %}

{% block content %}
<br><br><br>
<div class="jumbotron text-center">
    <h1 class="display-3">Thank You!</h1>
    <p class="lead"><strong>We have recieved your Email.</strong> We will get back to you at the earliest.</p>
    <hr>
    <p>
        Having trouble? <a href="{{url_for('view.contact')}}">Contact us</a>
    </p>
    <p class="lead">
        <a class="btn btn-primary btn-sm" href="{{url_for('view.hello')}}" role="button">Continue to homepage</a>
    </p>
</div>
<br><br><br>
{% endblock %}